name: thinking_battle
description: This is a online lateral thinking battle app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.17.0-nullsafety.0
  hooks_riverpod: ^0.14.0+4
  audioplayers: ^0.19.1
  awesome_dialog: ^2.1.1
  flutter_spinkit: "^5.1.0"
  lottie: ^1.1.0
  package_info: ^2.0.2
  url_launcher: ^6.0.10
  app_review: ^2.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1

  flutter_lints: ^1.0.0

flutter_native_splash:
  image: "assets/icons/small-logo.jpg"
  color: "000000"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/lottie/

  fonts:
    - family: NotoSerifJP
      fonts:
        - asset: assets/fonts/NotoSerifJP-Regular.otf
        - asset: assets/fonts/NotoSerifJP-Bold.otf
          weight: 700
    - family: YuseiMagic
      fonts:
        - asset: assets/fonts/YuseiMagic-Regular.ttf
    - family: SawarabiGothic
      fonts:
        - asset: assets/fonts/SawarabiGothic-Regular.ttf
