name: thinking_battle
description: This is a online lateral thinking battle app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.17.0-nullsafety.0
  hooks_riverpod: ^0.14.0+4
  shared_preferences: ^2.0.5
  audioplayers: ^0.19.1
  awesome_dialog: ^2.1.1
  flutter_spinkit: "^5.1.0"
  lottie: ^1.1.0
  package_info: ^2.0.2
  url_launcher: ^6.0.10
  app_review: ^2.1.1+1
  intl: ^ 0.17.0
  bubble: ^1.2.1
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_remote_config: ^0.11.0
  flutter_easyloading: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1

  flutter_lints: ^1.0.0

flutter_native_splash:
  image: "assets/icons/small-logo.jpg"
  color: "000000"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/lottie/

  fonts:
    - family: KaiseiOpti
      fonts:
        - asset: assets/fonts/KaiseiOpti-Regular.ttf
        - asset: assets/fonts/KaiseiOpti-Bold.ttf
          weight: 700
    - family: ReggaeOne
      fonts:
        - asset: assets/fonts/Stick-Regular.ttf
    - family: KiwiMaru
      fonts:
        - asset: assets/fonts/KiwiMaru-Regular.ttf
